Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLNhaSach.Data;
using QLNhaSach.Models;

namespace QLNhaSach.Controllers
{
    public class BillController : Controller
    {
        private readonly QLNhaSachContext _context;
        private readonly Cart _cart;

        public BillController(QLNhaSachContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }
        public async Task<IActionResult> Index()
        {
            return _context.Bills != null ?
                        View(await _context.Bills.ToListAsync()) :
                        Problem("Entity set 'QLNhaSachContext.Bills'  is null.");
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Bill bill)
        {
            var cartItems = _cart.GetAllCartItems();
            _cart.CartItems = cartItems;

            if (_cart.CartItems.Count == 0)
            {
                ModelState.AddModelError("", "Cart is empty, please add a book first.");
            }

            if (ModelState.IsValid)
            {
                CreateBill(bill);
                _cart.ClearCart();
                return RedirectToAction("CheckoutComplete", new { billId = bill.Id });
            }

            return View(bill);
        }

        public IActionResult CheckoutComplete(int billId)
        {
            // Retrieve the bill with its items
            var bill = _context.Bills
                .Include(b => b.BillItems)
                .ThenInclude(bi => bi.Book)
                .FirstOrDefault(b => b.Id == billId);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bill/CheckoutComplete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckoutComplete(Bill bill)
        {
            foreach (var item in bill.BillItems)
            {
                var book = await _context.Books.FindAsync(item.BookId);
                if (book != null)
                {
                    book.NumOfBook -= item.Quantity;
                    if (book.NumOfBook < 0)
                    {
                        book.NumOfBook = 0;
                    }
                    await _context.SaveChangesAsync();
                }
            }
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public void CreateBill(Bill bill)
        {
            bill.BillDate = DateTime.Now;

            var cartItems = _cart.CartItems;

            foreach (var item in cartItems)
            {
                var orderItem = new BillItem()
                {
                    Quantity = item.Quantity,
                    BookId = item.Book.BookId,
                    BillId = bill.Id,
                    Price = item.Book.Price * item.Quantity
                };
                bill.BillItems.Add(orderItem);
                bill.BillTotal += orderItem.Price;
            }
            _context.Bills.Add(bill);
            _context.SaveChanges();
        }
        // GET: Bill/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var bill = await _context.Bills
                .Include(b => b.BillItems)
                .ThenInclude(bi => bi.Book)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }
        // GET: Bill/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var bill = await _context.Bills
                .Include(b => b.BillItems)
                    .ThenInclude(bi => bi.Book)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bill/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bill = await _context.Bills.FindAsync(id);

            if (bill != null)
            {
                _context.BillItems.RemoveRange(bill.BillItems);
                await _context.SaveChangesAsync();
                _context.Bills.Remove(bill);
                await _context.SaveChangesAsync();

            }
           
            return RedirectToAction(nameof(Index)); 
        }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLNhaSach.Models;
using QLNhaSach.Data;

namespace QLNhaSach.Controllers
{
    public class BooksController : Controller
    {
        private readonly QLNhaSachContext _context;

        public BooksController(QLNhaSachContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
              return _context.Books != null ? 
                          View(await _context.Books.ToListAsync()) :
                          Problem("Entity set 'QLNhaSachContext.Book'  is null.");
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,BookName,Description,Author,Language,Publisher,BookStatus,Price,NumOfBook,ImageUrl")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookId,BookName,Description,Author,Language,Publisher,BookStatus,Price,NumOfBook,ImageUrl")] Book book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Books == null)
            {
                return Problem("Entity set 'QLNhaSachContext.Book'  is null.");
            }
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.Books?.Any(e => e.BookId == id)).GetValueOrDefault();
        }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QLNhaSach.Models;
using QLNhaSach.Data;

namespace QLNhaSach.Controllers
{
    
    public class CartController : Controller
    {
        private readonly QLNhaSachContext _context;
        private readonly Cart _cart;

        public CartController(QLNhaSachContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }

        public IActionResult Index()
        {
            var items = _cart.GetAllCartItems();
            _cart.CartItems = items;

            return View(_cart);
        }

        public IActionResult AddToCart(int id)
        {
            var selectedBook = GetBookById(id);

            if (selectedBook != null)
            {
                _cart.AddToCart(selectedBook, 1);
            }

            return RedirectToAction("Index", "Store");
        }

        public IActionResult RemoveFromCart(int id)
        {
            var selectedBook = GetBookById(id);

            if (selectedBook != null)
            {
                _cart.RemoveFromCart(selectedBook);
            }

            return RedirectToAction("Index");
        }

        public IActionResult ReduceQuantity(int id)
        {
            var selectedBook = GetBookById(id);

            if (selectedBook != null)
            {
                _cart.ReduceQuantity(selectedBook);
            }

            return RedirectToAction("Index");
        }

        public IActionResult IncreaseQuantity(int id)
        {
            var selectedBook = GetBookById(id);

            if (selectedBook != null)
            {
                _cart.IncreaseQuantity(selectedBook);
            }

            return RedirectToAction("Index");
        }

        public IActionResult ClearCart()
        {
            _cart.ClearCart();

            return RedirectToAction("Index");
        }

        public Book GetBookById(int id)
        {
            return _context.Books.FirstOrDefault(b => b.BookId == id);
        }
    }
}

Controllers/StoragesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLNhaSach.Data;
using QLNhaSach.Models;

namespace QLNhaSach.Controllers
{
    public class StoragesController : Controller
    {
        private readonly QLNhaSachContext _context;

        public StoragesController(QLNhaSachContext context)
        {
            _context = context;
        }

        // GET: Storages
        public async Task<IActionResult> Index()
        {
            ViewBag.Books = await _context.Books
                                          .ToDictionaryAsync(b => b.BookId, b => b);
            return _context.Storage != null ? 
                          View(await _context.Storage.ToListAsync()) :
                          Problem("Entity set 'QLNhaSachContext.Storage'  is null.");
        }


        // GET: Storages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Storage == null)
            {
                return NotFound();
            }

            var storage = await _context.Storage
                .FirstOrDefaultAsync(m => m.StorageID == id);
            if (storage == null)
            {
                return NotFound();
            }

            return View(storage);
        }

        // GET: Storages/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.StorageBook = new SelectList(await _context.Books.ToListAsync(), "BookId", "BookName");
            return View();
        }

        // POST: Storages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StorageID,BookId,Transfer,Cost,Note")] Storage storage)
        {
            ViewBag.StorageBook = new SelectList(await _context.Books.ToListAsync(), "BookId", "BookName");
            if (ModelState.IsValid)
            {
                var book = await _context.Books.FindAsync(storage.BookId);
                if (book != null)
                {
                    book.NumOfBook += storage.Transfer;

                    _context.Add(storage);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(storage);
        }

        // GET: Storages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Storage == null)
            {
                return NotFound();
            }

            var storage = await _context.Storage.FindAsync(id);
            if (storage == null)
            {
                return NotFound();
            }
            return View(storage);
        }

        // POST: Storages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StorageID,BookId,Transfer,Cost,Note")] Storage storage)
        {
            if (id != storage.StorageID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(storage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StorageExists(storage.StorageID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(storage);
        }

        // GET: Storages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Storage == null)
            {
                return NotFound();
            }

            var storage = await _context.Storage
                .FirstOrDefaultAsync(m => m.StorageID == id);
            if (storage == null)
            {
                return NotFound();
            }

            return View(storage);
        }

        // POST: Storages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Storage == null)
            {
                return Problem("Entity set 'QLNhaSachContext.Storage'  is null.");
            }
            var storage = await _context.Storage.FindAsync(id);
            if (storage != null)
            {
                _context.Storage.Remove(storage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StorageExists(int id)
        {
          return (_context.Storage?.Any(e => e.StorageID == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QLNhaSach</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLNhaSach.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/myCss.css" />
    <link rel="stylesheet" href="~/css/sidebar.css" />
</head>
<body>
    <div class="wrapper">
         @if (User.IsInRole("Admin"))
                    {
        <nav id="sidebar">
            <ul class="list-unstyled components">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Books" asp-action="Index"><i class="fas fa-chalkboard-teacher"></i> Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Complains" asp-action="Index"><i class="fas fa-user-graduate"></i> Complain</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Bill" asp-action="Index"><i class="fas fa-building"></i> Bill</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Storages" asp-action="Index"><i class="fas fa-clipboard-list"></i> Storages</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="ListAllRoles"><i class="fas fa-user-tie"></i> Admin</a>
                </li>
            </ul>

        </nav>
        }
        <div id="content">
            <nav class="navbar navbar-expand-lg bg-light navbar-light fixed-top">
                <div class="container-fluid d-flex">
                    @if (User.IsInRole("Admin"))
                    {
                        <button class="btn btn-info d-inline-flex align-items-center" type="button" id="sidebarCollapse">
                            <i class="fas fa-align-left"></i><span class="ml-2">Admin</span>
                        </button>
                        <button class="btn btn-dark d-inline-flex d-lg-none align-items-center ml-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-align-justify"></i>
                        </button>
                    }

                    <div class="collapse navbar-collapse d-flex w-100" id="navbarSupportedContent">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item active">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" asp-area="" asp-controller="Store" asp-action="Index"><i class="fas fa-home"></i> Store</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" asp-area="" asp-controller="Complains" asp-action="Create"><i class="fas fa-home"></i> Complains</a>
                            </li>
                        </ul>
                        
                        <ul class="navbar-nav d-flex align-items-center">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a>
                            </li>
                            <li class="nav-item">
                                <partial name="_LoginPartial" />
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div>
                @RenderBody()
            </div>
        </div>

    </div>
   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sidebar.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
@*  <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QLNhaSach</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bill" asp-action="Index">Bill</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Storages" asp-action="Index">Storage</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ListAllRoles">Roles</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                    <a class="nav-link text-dark float-right" asp-area="" asp-controller="Cart" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div> *@