Models/Bill.cs
namespace QLNhaSach.Models
{
    public class Bill
    {
        public int Id { get; set; }
        public List<BillItem> BillItems { get; set; } = new();
        public int BillTotal { get; set; }
        public DateTime BillDate { get; set; }
    }
}

Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLNhaSach.Data;
using QLNhaSach.Models;

namespace QLNhaSach.Controllers
{
    public class BillController : Controller
    {
        private readonly QLNhaSachContext _context;
        private readonly Cart _cart;

        public BillController(QLNhaSachContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }
        public async Task<IActionResult> Index()
        {
            return _context.Bills != null ?
                        View(await _context.Bills.ToListAsync()) :
                        Problem("Entity set 'QLNhaSachContext.Bills'  is null.");
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Bill bill)
        {
            var cartItems = _cart.GetAllCartItems();
            _cart.CartItems = cartItems;

            if (_cart.CartItems.Count == 0)
            {
                ModelState.AddModelError("", "Cart is empty, please add a book first.");
            }

            if (ModelState.IsValid)
            {
                CreateBill(bill);
                _cart.ClearCart();
                return RedirectToAction("CheckoutComplete", new { billId = bill.Id });
            }

            return View(bill);
        }

        public IActionResult CheckoutComplete(int billId)
        {
            // Retrieve the bill with its items
            var bill = _context.Bills
                .Include(b => b.BillItems)
                .ThenInclude(bi => bi.Book)
                .FirstOrDefault(b => b.Id == billId);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bill/CheckoutComplete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckoutComplete(Bill bill)
        {
            foreach (var item in bill.BillItems)
            {
                var book = await _context.Books.FindAsync(item.BookId);
                if (book != null)
                {
                    book.NumOfBook -= item.Quantity;
                    if (book.NumOfBook < 0)
                    {
                        book.NumOfBook = 0;
                    }
                    await _context.SaveChangesAsync();
                }
            }
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public void CreateBill(Bill bill)
        {
            bill.BillDate = DateTime.Now;

            var cartItems = _cart.CartItems;

            foreach (var item in cartItems)
            {
                var orderItem = new BillItem()
                {
                    Quantity = item.Quantity,
                    BookId = item.Book.BookId,
                    BillId = bill.Id,
                    Price = item.Book.Price * item.Quantity
                };
                bill.BillItems.Add(orderItem);
                bill.BillTotal += orderItem.Price;
            }
            _context.Bills.Add(bill);
            _context.SaveChanges();
        }
        // GET: Bill/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var bill = await _context.Bills
                .Include(b => b.BillItems)
                .ThenInclude(bi => bi.Book)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }
        // GET: Bill/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var bill = await _context.Bills
                .Include(b => b.BillItems)
                    .ThenInclude(bi => bi.Book)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bill/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bill = await _context.Bills.FindAsync(id);

            if (bill != null)
            {
                _context.BillItems.RemoveRange(bill.BillItems);
                await _context.SaveChangesAsync();
                _context.Bills.Remove(bill);
                await _context.SaveChangesAsync();

            }
           
            return RedirectToAction(nameof(Index)); 
        }
    }
}

Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLNhaSach.Data;
using System.Linq;
using System.Threading.Tasks;

namespace QLNhaSach.Controllers
{
    [Authorize]
    public class StoreController : Controller
    {
        private readonly QLNhaSachContext _context;

        public StoreController(QLNhaSachContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchString, decimal? minPrice, decimal? maxPrice)
        {
            var books = from b in _context.Books
                        select b;

            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.BookName.Contains(searchString) || s.Author.Contains(searchString));
            }

            if (minPrice.HasValue)
            {
                books = books.Where(s => s.Price >= minPrice.Value);
            }

            if (maxPrice.HasValue)
            {
                books = books.Where(s => s.Price <= maxPrice.Value);
            }

            return View(await books.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
    }
}

Views/Bill/CheckOut.cshtml
@model Bill

<form asp-action="Checkout" method="post" class="form-horizontal" role="form">
    <h4>Please confirm your purchase</h4>
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Complete Bill" />
        </div>
    </div>
</form>

Views/Bill/CheckoutComplete.cshtml
@model QLNhaSach.Models.Bill

<h1>Thank you for your purchase!</h1>

<h5 class="mt-5">Bill Id: @Model.Id</h5>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Book</th>
            <th>Price</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BillItems)
        {
            var itemTotal = item.Book.Price * item.Quantity;
            <tr>
                <td>
                    <a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.BookId"><img src="@item.Book.ImageUrl" style="height: 4em"></a>
                </td>
                <td>
                    <a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.BookId">@item.Book.BookName</a>
                </td>
                <td>
                    @itemTotal.ToString("c")
                </td>
                <td>
                    @item.Quantity
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
    <td></td>
    <td class="text-right">
        <strong>Total:</strong>
    </td>
    <td>
        <strong>@Model?.BillTotal.ToString("c")</strong>
    </td>
    <td></td>
    </tfoot>
</table>

Views/Bill/Delete.cshtml
@model QLNhaSach.Models.Bill

@{
    ViewData["Title"] = "Delete Bill";
}

<h1>Delete Bill</h1>

<h3>Are you sure you want to delete this bill?</h3>
<div>
    <h4>Bill</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Bill Date
        </dt>
        <dd class="col-sm-10">
            @Model.BillDate
        </dd>
        <dt class="col-sm-2">
            Bill Total
        </dt>
        <dd class="col-sm-10">
            @Model.BillTotal
        </dd>
        <dt class="col-sm-2">
            Bill Items
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach (var item in Model.BillItems)
                {
                    <li>@item.Book.BookName (Quantity: @item.Quantity, Price: @item.Price)</li>
                }
            </ul>
        </dd>
    </dl>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>
</div>

Views/Bill/Details.cshtml
@model QLNhaSach.Models.Bill

@{
    ViewData["Title"] = "Bill Details";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Bill</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BillDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BillDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BillTotal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BillTotal)
        </dd>
    </dl>
</div>

<h4>Items</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BillItems[0].Book.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillItems[0].Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillItems[0].Price)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.BillItems)
        {
            <tr>
                <td>@item.Book.BookName</td>
                <td>@item.Quantity</td>
                <td>@item.Price</td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a href="@Url.Action("Index", "Bill")">Back to List</a>
</p>

Views/Bill/Index.cshtml
@model IEnumerable<QLNhaSach.Models.Bill>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BillTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BillTotal).000VND
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillDate)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success"><i class="fa-solid fa-circle-info"></i></a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>